version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        environment:
            - ENV=development

volumes:
    node_modules: