name: Docker Build Check and Tag Version

on:
  pull_request:
    branches:
      - main

jobs:
  docker-build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build . -t my-image:pr-check

  create-tag:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Tag
        run: |
          VERSION=v1.$(date +'%Y%m%d%H%M')
          git tag $VERSION
          git push origin $VERSION
