name: Docker Build Check and Tag Version

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running tests..."
          # ใส่คำสั่งรัน test ของคุณ

      - name: Create tag
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="v1.0.$(date +%s)" # หรือดึง version จากไฟล์
          git tag $VERSION
          git push origin $VERSION
          echo "::set-output name=tag::$VERSION"
