name: Push Workflow

on:
  push:
    tags:
      - 'v*' # Match tags starting with 'v'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy code
        run: |
          echo "Deploying version $GITHUB_REF_NAME"
          # Add your deployment commands here
