name: Push Tag and Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Read Version File
      id: read-version
      run: |
        VERSION=$(cat version.txt)
        echo "Version from file: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Output version
      run: echo "New version is ${{ env.VERSION }}"

    - name: Build Docker image
      id: build-docker
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/web-grader:${{ env.VERSION }} .
      continue-on-error: true

    - name: Push Docker image
      id: push-docker
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/web-grader:${{ env.VERSION }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/web-grader:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/web-grader:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/web-grader:latest
      continue-on-error: true

    - name: Remove Tag if Push Fails
      if: failure() || steps.push-docker.outcome == 'failure' || steps.build-docker.outcome == 'failure'
      run: |
        echo "Push failed, deleting tag..."
        git fetch --tags
        git tag -d ${{ env.VERSION }} || echo "Tag not found locally, skipping deletion..."
        git push --delete origin ${{ env.VERSION }} || echo "Tag not found on remote, skipping deletion..."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Remove version file
      run: |
        rm version.txt
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Remove version.txt"
        git push
