name: Push Workflow

on:
  push:
    branch:
      - main
    tags:
      - 'v*' # ใช้ pattern ของ tag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy code
        run: |
          echo "Deploying version $GITHUB_REF_NAME"
          # ใส่คำสั่ง deploy ของคุณ 
